[2021-05-16 05:21:05,871] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: json_data_ingesation.process_json 2021-05-16T05:19:42.083662+00:00 [queued]>
[2021-05-16 05:21:05,881] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: json_data_ingesation.process_json 2021-05-16T05:19:42.083662+00:00 [queued]>
[2021-05-16 05:21:05,881] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2021-05-16 05:21:05,881] {taskinstance.py:867} INFO - Starting attempt 1 of 2
[2021-05-16 05:21:05,881] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2021-05-16 05:21:05,891] {taskinstance.py:887} INFO - Executing <Task(PythonOperator): process_json> on 2021-05-16T05:19:42.083662+00:00
[2021-05-16 05:21:05,893] {standard_task_runner.py:53} INFO - Started process 1890 to run task
[2021-05-16 05:21:05,941] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: json_data_ingesation.process_json 2021-05-16T05:19:42.083662+00:00 [running]> ip-172-31-21-147.ec2.internal
[2021-05-16 05:21:05,953] {taskinstance.py:1128} ERROR - [Errno 2] No such file or directory: 'C:/Users/priye/PycharmProjects/condenast/src1/'
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ubuntu/airflow/dags/process_utils.py", line 10, in process_json
    if os.listdir(src_dir):
OSError: [Errno 2] No such file or directory: 'C:/Users/priye/PycharmProjects/condenast/src1/'
[2021-05-16 05:21:05,957] {taskinstance.py:1151} INFO - Marking task as UP_FOR_RETRY
[2021-05-16 05:21:15,865] {logging_mixin.py:112} INFO - [2021-05-16 05:21:15,865] {local_task_job.py:103} INFO - Task exited with return code 1
