[2021-06-27 04:51:12,178] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: csv_data_ingesation.csv_file_check 2021-06-26T00:00:00+00:00 [queued]>
[2021-06-27 04:51:12,185] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: csv_data_ingesation.csv_file_check 2021-06-26T00:00:00+00:00 [queued]>
[2021-06-27 04:51:12,185] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2021-06-27 04:51:12,185] {taskinstance.py:867} INFO - Starting attempt 1 of 2
[2021-06-27 04:51:12,185] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2021-06-27 04:51:12,194] {taskinstance.py:887} INFO - Executing <Task(BashOperator): csv_file_check> on 2021-06-26T00:00:00+00:00
[2021-06-27 04:51:12,196] {standard_task_runner.py:53} INFO - Started process 1914 to run task
[2021-06-27 04:51:12,245] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: csv_data_ingesation.csv_file_check 2021-06-26T00:00:00+00:00 [running]> ip-172-31-21-147.ec2.internal
[2021-06-27 04:51:12,257] {bash_operator.py:82} INFO - Tmp dir root location: 
 /tmp
[2021-06-27 04:51:12,259] {bash_operator.py:105} INFO - Temporary script location: /tmp/airflowtmpARrThR/csv_file_checkTU2Exw
[2021-06-27 04:51:12,259] {bash_operator.py:115} INFO - Running command: shasum ~/airflow/datasources/src2/data*
[2021-06-27 04:51:12,264] {bash_operator.py:122} INFO - Output:
[2021-06-27 04:51:12,289] {bash_operator.py:126} INFO - shasum: /home/ubuntu/airflow/datasources/src2/data*:
[2021-06-27 04:51:12,289] {bash_operator.py:130} INFO - Command exited with return code 1
[2021-06-27 04:51:12,296] {taskinstance.py:1128} ERROR - Bash command failed
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
AirflowException: Bash command failed
[2021-06-27 04:51:12,297] {taskinstance.py:1151} INFO - Marking task as UP_FOR_RETRY
[2021-06-27 04:51:22,177] {logging_mixin.py:112} INFO - [2021-06-27 04:51:22,176] {local_task_job.py:103} INFO - Task exited with return code 1
