[2021-06-27 04:49:37,275] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: json_data_ingesation.json_file_check 2021-06-26T00:00:00+00:00 [queued]>
[2021-06-27 04:49:37,283] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: json_data_ingesation.json_file_check 2021-06-26T00:00:00+00:00 [queued]>
[2021-06-27 04:49:37,283] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2021-06-27 04:49:37,284] {taskinstance.py:867} INFO - Starting attempt 1 of 2
[2021-06-27 04:49:37,284] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2021-06-27 04:49:37,301] {taskinstance.py:887} INFO - Executing <Task(BashOperator): json_file_check> on 2021-06-26T00:00:00+00:00
[2021-06-27 04:49:37,303] {standard_task_runner.py:53} INFO - Started process 1831 to run task
[2021-06-27 04:49:37,363] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: json_data_ingesation.json_file_check 2021-06-26T00:00:00+00:00 [running]> ip-172-31-21-147.ec2.internal
[2021-06-27 04:49:37,376] {bash_operator.py:82} INFO - Tmp dir root location: 
 /tmp
[2021-06-27 04:49:37,378] {bash_operator.py:105} INFO - Temporary script location: /tmp/airflowtmpi9jl2H/json_file_checkx42Ux_
[2021-06-27 04:49:37,378] {bash_operator.py:115} INFO - Running command: shasum ~/airflow/datasources/src1/data*
[2021-06-27 04:49:37,383] {bash_operator.py:122} INFO - Output:
[2021-06-27 04:49:37,467] {bash_operator.py:126} INFO - shasum: /home/ubuntu/airflow/datasources/src1/data*:
[2021-06-27 04:49:37,468] {bash_operator.py:130} INFO - Command exited with return code 1
[2021-06-27 04:49:37,475] {taskinstance.py:1128} ERROR - Bash command failed
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
AirflowException: Bash command failed
[2021-06-27 04:49:37,478] {taskinstance.py:1151} INFO - Marking task as UP_FOR_RETRY
[2021-06-27 04:49:47,272] {logging_mixin.py:112} INFO - [2021-06-27 04:49:47,272] {local_task_job.py:103} INFO - Task exited with return code 1
