[2021-06-27 04:50:45,759] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: json_data_ingesation.json_file_check 2021-06-26T00:00:00+00:00 [queued]>
[2021-06-27 04:50:45,766] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: json_data_ingesation.json_file_check 2021-06-26T00:00:00+00:00 [queued]>
[2021-06-27 04:50:45,766] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2021-06-27 04:50:45,766] {taskinstance.py:867} INFO - Starting attempt 2 of 2
[2021-06-27 04:50:45,766] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2021-06-27 04:50:45,775] {taskinstance.py:887} INFO - Executing <Task(BashOperator): json_file_check> on 2021-06-26T00:00:00+00:00
[2021-06-27 04:50:45,778] {standard_task_runner.py:53} INFO - Started process 1896 to run task
[2021-06-27 04:50:45,827] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: json_data_ingesation.json_file_check 2021-06-26T00:00:00+00:00 [running]> ip-172-31-21-147.ec2.internal
[2021-06-27 04:50:45,839] {bash_operator.py:82} INFO - Tmp dir root location: 
 /tmp
[2021-06-27 04:50:45,841] {bash_operator.py:105} INFO - Temporary script location: /tmp/airflowtmpG0Sg5a/json_file_checkKVHXKJ
[2021-06-27 04:50:45,841] {bash_operator.py:115} INFO - Running command: shasum ~/airflow/datasources/src1/data*
[2021-06-27 04:50:45,849] {bash_operator.py:122} INFO - Output:
[2021-06-27 04:50:45,873] {bash_operator.py:126} INFO - shasum: /home/ubuntu/airflow/datasources/src1/data*:
[2021-06-27 04:50:45,874] {bash_operator.py:130} INFO - Command exited with return code 1
[2021-06-27 04:50:45,881] {taskinstance.py:1128} ERROR - Bash command failed
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
AirflowException: Bash command failed
[2021-06-27 04:50:45,882] {taskinstance.py:1170} INFO - All retries failed; marking task as FAILED.dag_id=json_data_ingesation, task_id=json_file_check, execution_date=20210626T000000, start_date=20210627T045045, end_date=20210627T045045
[2021-06-27 04:50:55,758] {logging_mixin.py:112} INFO - [2021-06-27 04:50:55,758] {local_task_job.py:103} INFO - Task exited with return code 1
