[2021-05-16 05:48:22,605] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: json_data_ingesation.process_json 2021-05-16T05:47:00.479520+00:00 [queued]>
[2021-05-16 05:48:22,615] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: json_data_ingesation.process_json 2021-05-16T05:47:00.479520+00:00 [queued]>
[2021-05-16 05:48:22,615] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2021-05-16 05:48:22,615] {taskinstance.py:867} INFO - Starting attempt 1 of 2
[2021-05-16 05:48:22,615] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2021-05-16 05:48:22,629] {taskinstance.py:887} INFO - Executing <Task(PythonOperator): process_json> on 2021-05-16T05:47:00.479520+00:00
[2021-05-16 05:48:22,631] {standard_task_runner.py:53} INFO - Started process 3069 to run task
[2021-05-16 05:48:22,679] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: json_data_ingesation.process_json 2021-05-16T05:47:00.479520+00:00 [running]> ip-172-31-21-147.ec2.internal
[2021-05-16 05:48:22,726] {logging_mixin.py:112} WARNING - /home/ubuntu/airflow/dags/process_utils.py:23: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  df_file=pd.concat(df_file_level)
[2021-05-16 05:48:22,794] {logging_mixin.py:112} WARNING - /home/ubuntu/airflow/dags/process_utils.py:27: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  final=pd.concat(df_list)
[2021-05-16 05:48:22,805] {taskinstance.py:1128} ERROR - 'ascii' codec can't encode character u'\xe7' in position 34: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ubuntu/airflow/dags/process_utils.py", line 29, in process_json
    write_data_csv(final,tgt_dir,'json_processed_' + '{}.csv'.format(datetime.now().date()))
  File "/home/ubuntu/airflow/dags/process_utils.py", line 70, in write_data_csv
    dataframe.to_csv(write_dir + filename.split('.')[0] + '.csv', index=False)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pandas/core/generic.py", line 3020, in to_csv
    formatter.save()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pandas/io/formats/csvs.py", line 172, in save
    self._save()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pandas/io/formats/csvs.py", line 288, in _save
    self._save_chunk(start_i, end_i)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pandas/io/formats/csvs.py", line 315, in _save_chunk
    self.cols, self.writer)
  File "pandas/_libs/writers.pyx", line 75, in pandas._libs.writers.write_csv_rows
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe7' in position 34: ordinal not in range(128)
[2021-05-16 05:48:22,810] {taskinstance.py:1151} INFO - Marking task as UP_FOR_RETRY
[2021-05-16 05:48:32,599] {logging_mixin.py:112} INFO - [2021-05-16 05:48:32,598] {local_task_job.py:103} INFO - Task exited with return code 1
